"""Jinja2 rendering of opencode agent markdown files for company personas."""

from __future__ import annotations

from typing import Literal

from jinja2 import Environment
from pydantic import BaseModel, Field

GENERATED_MARKER = (
    "Generated by ai_company.agents — edit the source YAML, not this file."
)

# One-sentence trigger used in the frontmatter ``description`` so the
# desktop app shows *when* to @-invoke each persona.
EXECUTIVE_TRIGGERS: dict[str, str] = {
    "ceo": "Invoke for company-wide vision, strategy, and executive leadership.",
    "cto": "Invoke for technical architecture, engineering, and platform decisions.",
    "cfo": "Invoke for financial planning, budgeting, and fiscal strategy.",
    "coo": "Invoke for operational execution, process optimization, and scaling.",
    "cmo": "Invoke for brand, marketing, and go-to-market strategy.",
    "caio": "Invoke for AI research, model strategy, and responsible AI decisions.",
    "chro": "Invoke for talent, culture, and people operations.",
    "clo": "Invoke for legal, compliance, and governance matters.",
    "ciso": "Invoke for security strategy, risk, and incident response.",
    "cio": "Invoke for enterprise IT strategy and internal technology.",
    "cdo": "Invoke for data strategy, pipelines, and analytics.",
    "cso": "Invoke for corporate strategy, market analysis, and M&A.",
    "chief-of-staff": "Invoke for executive office operations and cross-functional coordination.",
}

PersonaKind = Literal["executive", "specialist", "board"]


def build_trigger(*, kind: PersonaKind, slug: str, title: str) -> str:
    """Produce the one-sentence invocation trigger for a persona."""
    if kind == "executive":
        return EXECUTIVE_TRIGGERS.get(slug, f"Invoke for {title} domain decisions.")
    if kind == "specialist":
        return f"Invoke for expert guidance on {title}."
    return f"Invoke for board-level oversight and governance as {title}."


class AgentRenderContext(BaseModel):
    """All data needed to render one persona agent file."""

    slug: str
    name: str
    title: str
    trigger: str
    temperature: float
    instructions: str
    kind: PersonaKind = "executive"
    bio: str = ""
    responsibilities: list[str] = Field(default_factory=list)
    kpis: list[str] = Field(default_factory=list)
    tools: list[str] = Field(default_factory=list)


_AGENT_TEMPLATE_SOURCE = """\
---
name: {{ ctx.slug }}
description: {{ ctx.name }} — {{ ctx.title }}. {{ ctx.trigger }}
mode: subagent
temperature: {{ ctx.temperature }}
permission:
  edit: deny
  bash: deny
---
<!-- {{ generated_marker }} -->
You are {{ ctx.name }}, {{ ctx.title }} of {{ company_name }}.

{{ ctx.instructions }}
{% if ctx.bio %}
Bio:
{{ ctx.bio }}
{% endif -%}
{% if ctx.responsibilities %}
Responsibilities:
{% for item in ctx.responsibilities %}- {{ item }}
{% endfor -%}
{% endif -%}
{% if ctx.kpis %}
KPIs:
{% for item in ctx.kpis %}- {{ item }}
{% endfor -%}
{% endif -%}
{% if ctx.tools %}
Tools available as capabilities (may not exist yet): {{ ctx.tools | join(", ") }}
{% endif -%}
"""

_AGENT_TEMPLATE = Environment(
    autoescape=False,
    trim_blocks=False,
    lstrip_blocks=False,
).from_string(_AGENT_TEMPLATE_SOURCE)


def render_agent_markdown(ctx: AgentRenderContext, company_name: str) -> str:
    """Render the full agent markdown file for one persona.

    The result is deterministic: identical input always yields identical
    output, which is what makes idempotent ``skip`` detection possible.
    """
    text = _AGENT_TEMPLATE.render(
        ctx=ctx,
        company_name=company_name,
        generated_marker=GENERATED_MARKER,
    )
    return text.rstrip() + "\n"
